config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  resources :story, :about, :contact
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  prepend_view_path Rails.root.join("frontend")

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index; end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/story_controller.rb
class StoryController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contact/index.html.erb
<main role="main">
contact details
</main>

app/views/home/index.html.erb
<main role="main">
  <section class="about">
    <div class="video-wrapper">
      <div class="video-wrapper">
        <%= video_tag("demo-vid-1.mp4", "demo-vid-2.mp4", "demo-vid-3.mp4", autoplay: true, loop: true, muted: true, playsinline: true, class: 'can-play')%>
      </div>
      <div class="about__statement">
        <p id="test" class="about__statement__1">Paul Salter Consultancy.</p>
        <p class="about__statement__2">Insurance nonsense buzzwords <br> more silly words.</p>
      </div>
  </section>
</main>

app/views/layouts/_navigation.html.erb
<header class="masthead">
  <div class="container">
    <h1><a href="#">PSC</a></h1>
    <nav>
      <ul>
        <li><%= active_link_to('About', root_path, active: :exclusive) %></li>
        <li><%= active_link_to('Contact', contact_index_path) %></li>
        <li><%= active_link_to('Story', story_index_path) %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Paul Salter Consulting Ltd</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application', :defer => "defer" %>
    <%= render 'layouts/navigation' %>
  </head>
  <body class="section--home">
    <%= yield %>
  </body>
</html>

app/views/story/index.html.erb
<main role="main">
story here
</main>